title: Modelo VFT - Reportes de Ingeniería de Transportes en Urbanismo
author: Hernán Galileo Cabrera Garibaldi
#logo: notebooks/ASSETS/logo.png
execute:
  execute_notebooks: "off"

exclude_patterns:
  - venv
  - src
  - tmp
  - .github
  - .claude
  - .vscode